name: Go Test
on: [push, pull_request]
jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Setup Goveralls
      run: go install github.com/mattn/goveralls
    - name: Install Dependencies
      run: |
        go mod download
    - name: Run Tests
      run: go test -v -covermode=atomic -coverprofile=cov.out ./...
    - name: Run Coveralls
      run: goveralls -coverprofile=cov.out -service=github
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}