project_name: nats-rest-config-proxy

release:
  draft: true
  github:
    owner: nats-io
    name: nats-rest-config-proxy

  name_template: 'Release {{.Tag}}'

builds:
- id: nats-rest-config-proxy
  main: ./cmd/nats-rest-config-proxy/main.go
  binary: nats-rest-config-proxy
  env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386

- id: nats-rest-config-validator
  main: ./cmd/nats-rest-config-validator/main.go
  binary: nats-rest-config-validator
  env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386

- id: nats-rest-config-publish
  main: ./cmd/nats-rest-config-publish/main.go
  binary: nats-rest-config-publish
  env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386

- id: nats-rest-config-snapshot
  main: ./cmd/nats-rest-config-snapshot/main.go
  ldflags: -s -w
  binary: nats-rest-config-snapshot
  env:
    - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
  goarm:
  - 6
  - 7
  ignore:
  - goos: darwin
    goarch: 386

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    
checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^doc:'
    - '^test:'

nfpms:
- formats:
    - deb
  file_name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  bindir: /usr/local/bin
  description: A REST configuration proxy for the NATS server
  vendor: nats.io
  homepage: https://nats.io
  license: Apache 2.0
  maintainer: Synadia <info@synadia.com>
