name: Go Test
on: [pull_request]
jobs:
  test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup Dependencies
      run: |
        go mod download
        echo "127.0.0.1 nats-cluster.default.svc.cluster.local" | sudo tee -a /etc/hosts

    - name: Run Tests
      run: go test -v ./...
